- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  setPreference: true
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000 # 10 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobLawyer
      min: 14400 # Ronstation - 4 hours.
    - !type:CharacterWhitelistRequirement # Ronstation - Whitelist requirement because of their highly roleplay-based nature. Lawyers can become prosecutors.
  startingGear: ProsecutorGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-cj
  access:
  - Prosecutor
  - Justice
  - Security
  - Maintenance

- type: startingGear
  id: ProsecutorGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitProsecutor
    neck: ClothingNeckProsecutorbadge
    back: ClothingBackpackLawyerFilled
    shoes: ClothingShoesBootsLaceup
    id: ProsecutorPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtProsecutor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


