- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  setPreference: true
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000 # 5 hours.
    - !type:DepartmentTimeRequirement
      department: Epistemics
      min: 18000 # Ronstation - 5 hours.
    - !type:CharacterLogicOrRequirement
  #    requirements:
  #      - !type:CharacterSpeciesRequirement
  #        inverted: true
  #        species:
  #          - IPC
  #      - !type:CharacterTraitRequirement
  #        traits:
  #          - AnomalousPositronics
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 5 # DeltaV - From 4 to 5
  canBeAntag: false # Ronstation - Mantis is now a "warden" of science.
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Ronstation - Mantis is science's warden.
  #- !type:AddComponentSpecial
  #  components:
  #  - type: Psionic
  #    powerSlots: 2
  #- !type:AddComponentSpecial
  #  components:
  #  - type: InnatePsionicPowers
  #    powersToAdd:
  #      - MetapsionicPower
  #      - TelepathyPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
    # pocket2: ForensicScanner # DeltaV - Mantis is no longer a Detective
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled
