- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  setPreference: true
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000 # 5 hours.
    - !type:DepartmentTimeRequirement
      department: Command # Ronstation - Forensic Mantis replaced with Liaison Mantis.
      min: 0 #3600
    - !type:CharacterPlaytimeRequirement
      tracker: JobDetective # Ronstation - Liaison Mantis is inspector.
      min: 0 #18000 #Ronstation - 5 hours.
  #  - !type:CharacterLogicOrRequirement
  #    requirements:
  #      - !type:CharacterSpeciesRequirement
  #        inverted: true
  #        species:
  #          - IPC
  #      - !type:CharacterTraitRequirement
  #        traits:
  #          - AnomalousPositronics
  #  - !type:CharacterLogicOrRequirement # Ronstation - Unneeded speciesism.
  #    requirements:
  #      - !type:CharacterSpeciesRequirement
  #        inverted: true
  #        species:
  #          - Shadowkin
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-captain
  antagAdvantage: 5 # DeltaV - From 4 to 5
  canBeAntag: false # Ronstation - Mantis is now a command officer.
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  #special:
  #- !type:AddComponentSpecial
  #  components:
  #  - type: Psionic
  #    powerSlots: 2
  #- !type:AddComponentSpecial
  #  components:
  #  - type: InnatePsionicPowers
  #    powersToAdd:
  #      - MetapsionicPower
  #      - TelepathyPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetCommand # Ronstation - Mantis is part of Command
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
    # pocket2: ForensicScanner # DeltaV - Mantis is no longer a Detective
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled
